// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 8907ffca23
// Version Date: 2019年11月27日 星期三 21时28分21秒 UTC

package main

import (
	"flag"

	// This Service
	"github.com/OahcUil94/go-kit-training/gk-truss/echo-service/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	server.Run(server.DefaultConfig)
}
