// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello/pkg/grpc/pb/hello.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FooRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooRequest) Reset()         { *m = FooRequest{} }
func (m *FooRequest) String() string { return proto.CompactTextString(m) }
func (*FooRequest) ProtoMessage()    {}
func (*FooRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcfe1ed6ed0ceb4e, []int{0}
}

func (m *FooRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooRequest.Unmarshal(m, b)
}
func (m *FooRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooRequest.Marshal(b, m, deterministic)
}
func (m *FooRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooRequest.Merge(m, src)
}
func (m *FooRequest) XXX_Size() int {
	return xxx_messageInfo_FooRequest.Size(m)
}
func (m *FooRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FooRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FooRequest proto.InternalMessageInfo

type FooReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooReply) Reset()         { *m = FooReply{} }
func (m *FooReply) String() string { return proto.CompactTextString(m) }
func (*FooReply) ProtoMessage()    {}
func (*FooReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcfe1ed6ed0ceb4e, []int{1}
}

func (m *FooReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooReply.Unmarshal(m, b)
}
func (m *FooReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooReply.Marshal(b, m, deterministic)
}
func (m *FooReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooReply.Merge(m, src)
}
func (m *FooReply) XXX_Size() int {
	return xxx_messageInfo_FooReply.Size(m)
}
func (m *FooReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FooReply.DiscardUnknown(m)
}

var xxx_messageInfo_FooReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FooRequest)(nil), "pb.FooRequest")
	proto.RegisterType((*FooReply)(nil), "pb.FooReply")
}

func init() { proto.RegisterFile("hello/pkg/grpc/pb/hello.proto", fileDescriptor_fcfe1ed6ed0ceb4e) }

var fileDescriptor_fcfe1ed6ed0ceb4e = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcd, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2f, 0xc8, 0x4e, 0xd7, 0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0x2f, 0x48, 0xd2, 0x07, 0x8b,
	0xe8, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x31, 0x15, 0x24, 0x29, 0xf1, 0x70, 0x71, 0xb9, 0xe5,
	0xe7, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x71, 0x71, 0x71, 0x80, 0x79, 0x05, 0x39,
	0x95, 0x46, 0x3a, 0x5c, 0xac, 0x1e, 0x20, 0xc5, 0x42, 0xca, 0x5c, 0xcc, 0x6e, 0xf9, 0xf9, 0x42,
	0x7c, 0x7a, 0x05, 0x49, 0x7a, 0x08, 0xb5, 0x52, 0x3c, 0x70, 0x7e, 0x41, 0x4e, 0x65, 0x12, 0x1b,
	0xd8, 0x48, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x64, 0x0b, 0x6f, 0x73, 0x00, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	Foo(ctx context.Context, in *FooRequest, opts ...grpc.CallOption) (*FooReply, error)
}

type helloClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloClient(cc grpc.ClientConnInterface) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Foo(ctx context.Context, in *FooRequest, opts ...grpc.CallOption) (*FooReply, error) {
	out := new(FooReply)
	err := c.cc.Invoke(ctx, "/pb.Hello/Foo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	Foo(context.Context, *FooRequest) (*FooReply, error)
}

// UnimplementedHelloServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (*UnimplementedHelloServer) Foo(ctx context.Context, req *FooRequest) (*FooReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Foo not implemented")
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Foo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Foo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Hello/Foo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Foo(ctx, req.(*FooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Foo",
			Handler:    _Hello_Foo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello/pkg/grpc/pb/hello.proto",
}
