// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 8907ffca23
// Version Date: 2019年11月27日 星期三 21时28分21秒 UTC

// Package grpc provides a gRPC client for the Echo service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/OahcUil94/go-kit-training/gk-truss"
	"github.com/OahcUil94/go-kit-training/gk-truss/echo-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.EchoServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var echoEndpoint endpoint.Endpoint
	{
		echoEndpoint = grpctransport.NewClient(
			conn,
			"gk_truss.Echo",
			"Echo",
			EncodeGRPCEchoRequest,
			DecodeGRPCEchoResponse,
			pb.EchoResponse{},
			clientOptions...,
		).Endpoint()
	}

	var louderEndpoint endpoint.Endpoint
	{
		louderEndpoint = grpctransport.NewClient(
			conn,
			"gk_truss.Echo",
			"Louder",
			EncodeGRPCLouderRequest,
			DecodeGRPCLouderResponse,
			pb.EchoResponse{},
			clientOptions...,
		).Endpoint()
	}

	var loudergetEndpoint endpoint.Endpoint
	{
		loudergetEndpoint = grpctransport.NewClient(
			conn,
			"gk_truss.Echo",
			"LouderGet",
			EncodeGRPCLouderGetRequest,
			DecodeGRPCLouderGetResponse,
			pb.EchoResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		EchoEndpoint:      echoEndpoint,
		LouderEndpoint:    louderEndpoint,
		LouderGetEndpoint: loudergetEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCEchoResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC echo reply to a user-domain echo response. Primarily useful in a client.
func DecodeGRPCEchoResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.EchoResponse)
	return reply, nil
}

// DecodeGRPCLouderResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC louder reply to a user-domain louder response. Primarily useful in a client.
func DecodeGRPCLouderResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.EchoResponse)
	return reply, nil
}

// DecodeGRPCLouderGetResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC louderget reply to a user-domain louderget response. Primarily useful in a client.
func DecodeGRPCLouderGetResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.EchoResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCEchoRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain echo request to a gRPC echo request. Primarily useful in a client.
func EncodeGRPCEchoRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.EchoRequest)
	return req, nil
}

// EncodeGRPCLouderRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain louder request to a gRPC louder request. Primarily useful in a client.
func EncodeGRPCLouderRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.LouderRequest)
	return req, nil
}

// EncodeGRPCLouderGetRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain louderget request to a gRPC louderget request. Primarily useful in a client.
func EncodeGRPCLouderGetRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.LouderRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
