// Autogenerated code, do not change directly.
// To make changes to this file, please modify the templates at
// go-kit-middlewarer/tmpl/*.tmpl

// Package endpoint defines various different enpoint paths for transports
package endpoint

import (
	"gk-middlewarer/service"
)

const (
	// PathUppercase represents an endpoint path for Uppercase
	PathUppercase = "/uppercase"
	// PathCount represents an endpoint path for Count
	PathCount = "/count"
)

// StringServiceMiddleware defines a function that takes service.StringService and returns a service.StringService
type StringServiceMiddleware func(service.StringService) service.StringService
